Repository Tiryoh/docker-ros2-desktop-vnc, pull requests merged in 2021-06, with the labels that each got.

#28 fix the link to Foxy's Dockerfile
  README.md
Labels: Type: Documentation

#29 release: v1.1.0
  CHANGELOG.md
Labels: Type: Maintenance

#22 feat: Set foxy as the "latest" image
  .github/workflows/deploy.yml
  README.md
Labels: Type: Breaking Change, Type: Feature

#30 ci: Add ROS 2 Galactic
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  README.md
Labels: Type: CI, Type: Documentation

#20 feat: Add Dockerfile for dashing-arm64 to support Apple Silicon
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  dashing-arm64/Dockerfile
  dashing-arm64/ros-dashing-desktop.sh
Labels: Type: Feature

#32 chore: Add documentation update to CHANGELOG
  .chglog/config.yml
Labels: Type: Maintenance

#31 feat: Drop ROS 2 Dashing support
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  README.md
Labels: Type: Breaking Change, Type: Feature
